Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-08, with the labels that each got.

#382 Pharmacy - Fix occluded medication not applying after tourniquet is removed
  addons/pharma/CfgFunctions.hpp
Labels: kind/bug fix, status/tested

#380 Misc - Fix missing localized string for distance from patient hint
  addons/airway/functions/fnc_displayPatientInformation.sqf
  addons/main/script_macros.hpp
  addons/zeus/functions/fnc_menuPFH.sqf
Labels: kind/bug fix, status/tested

#386 Pharmacy - Fix String not found
  addons/pharma/XEH_preInit.sqf
Labels: kind/bug fix, status/tested

#387 Translation - Improve Japanese
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#390 Translation - 100% Spanish Fixed
  addons/surgery/stringtable.xml
Labels: area/translations

#370 Chemical - Fix Ace Mortar only showing gas rounds for rearm
  addons/chemical/CfgMagazineGroups.hpp
  addons/chemical/CfgWeapons.hpp
  addons/chemical/config.cpp
Labels: kind/bug fix, status/tested

#385 Chemical - Fix Post process effect creation failed error on server .rpt log.
  addons/chemical/XEH_postInit.sqf
  addons/chemical/functions/fnc_handleCSGas.sqf
Labels: kind/bug fix, status/tested

#378 Misc - Add interactions for better patient loading/unloading when carried
  addons/main/script_macros.hpp
  addons/misc/CfgEventHandlers.hpp
  addons/misc/CfgVehicles.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/functions/fnc_addVehicleCarryLoadActions.sqf
  addons/misc/functions/fnc_addVehicleUnloadCarryPatientActions.sqf
  addons/misc/functions/fnc_unloadAndCarryPatient.sqf
  addons/misc/stringtable.xml
Labels: kind/feature request, status/tested

#391 Improve Issue template | Add automated RPT parsing
  .github/ISSUE_TEMPLATE.md
  .github/workflows/extract-data-and-update-issue.yml
Labels: ignore changelog

#393 Pharmacy - Add Penthrox Inhaler
  addons/circulation/functions/fnc_AEDX_ViewMonitor_Charging.sqf
  addons/main/script_macros.hpp
  addons/misc/XEH_preInit.sqf
  addons/misc/script_component.hpp
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/CfgMagazines.hpp
  addons/pharma/CfgWeapons.hpp
  addons/pharma/XEH_PREP.hpp
  addons/pharma/XEH_postInit.sqf
  addons/pharma/XEH_preInit.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_Penthrox.sqf
  addons/pharma/script_component.hpp
  addons/pharma/sounds/use_penthrox.wav
  addons/pharma/stringtable.xml
  addons/pharma/ui/icon_penthrox.paa
Labels: kind/feature request, status/tested

#394 Circulation - Make CPR Continuous, AED improvements
  addons/breathing/functions/fnc_handleBreathing.sqf
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/CfgFunctions.hpp
  addons/circulation/CfgMoves.hpp
  addons/circulation/CfgVehicles.hpp
  addons/circulation/XEH_PREP.hpp
  addons/circulation/XEH_postInit.sqf
  addons/circulation/XEH_preInit.sqf
  addons/circulation/config.cpp
  addons/circulation/defines.hpp
  addons/circulation/functions/fnc_AEDX_ConnectVitalsMonitor.sqf
  addons/circulation/functions/fnc_AEDX_DisconnectVitalsMonitor.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor_AnalyzeFeedback.sqf
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
  addons/circulation/functions/fnc_AEDX_VitalsMonitor_CheckCondition.sqf
  addons/circulation/functions/fnc_AED_Analyze.sqf
  addons/circulation/functions/fnc_AED_Shock.sqf
  addons/circulation/functions/fnc_CPRStart.sqf
  addons/circulation/functions/fnc_Defibrillator_AttachPads.sqf
  addons/circulation/functions/fnc_Defibrillator_CheckCondition.sqf
  addons/circulation/functions/fnc_Defibrillator_Pads_CheckCondition.sqf
  addons/circulation/functions/fnc_Defibrillator_RemovePads.sqf
  addons/circulation/functions/fnc_cprLocal.sqf
  addons/circulation/functions/fnc_cprSuccess.sqf
  addons/circulation/functions/fnc_handleCardiacArrest.sqf
  addons/circulation/functions/fnc_placeAED.sqf
  addons/circulation/functions/fnc_updateHeartRate.sqf
  addons/circulation/sounds/checkpulse.wav
  addons/circulation/sounds/checkpulse_nopulsepushanalyze.wav
  addons/circulation/stringtable.xml
  addons/circulation/ui/AEDX_Monitor_Dialog.hpp
  addons/circulation/ui/AEDmode_bg.paa
  addons/main/script_macros.hpp
  addons/misc/functions/fnc_fullHealLocal.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
  addons/misc/functions/fnc_treatment.sqf
Labels: kind/feature request

#392 Breathing - Improve Pneumothorax, add medical menu visuals
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/XEH_PREP.hpp
  addons/breathing/XEH_preInit.sqf
  addons/breathing/functions/fnc_handleBreathing.sqf
  addons/breathing/functions/fnc_handlePulmoHit.sqf
  addons/breathing/functions/fnc_init.sqf
  addons/breathing/functions/fnc_inspectChest.sqf
  addons/breathing/functions/fnc_listenLungs.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_chestSealLocal.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_hemopneumothoraxLocal.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_tensionpneumothoraxLocal.sqf
  addons/breathing/script_component.hpp
  addons/breathing/stringtable.xml
  addons/circulation/CfgFunctions.hpp
  addons/circulation/XEH_PREP.hpp
  addons/circulation/functions/fnc_getBloodPressure.sqf
  addons/circulation/functions/fnc_updateBloodPressureChange.sqf
  addons/gui/data/body_image/leftarm_pulseoximeter.paa
  addons/gui/data/body_image/rightarm_pulseoximeter.paa
  addons/gui/data/body_image/torso_chestseal.paa
  addons/gui/data/body_image/torso_pneumothorax.paa
  addons/gui/functions/fnc_updateBodyImage.sqf
  addons/gui/functions/fnc_updateInjuryList.sqf
  addons/gui/gui.hpp
  addons/gui/script_component.hpp
  addons/main/script_macros.hpp
  addons/misc/functions/fnc_fullHealLocal.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
  addons/zeus/functions/fnc_ui_manageAirway.sqf
  addons/zeus/ui/RscAttributes.hpp
Labels: kind/feature request

#396 Airway - Add Cleared Airway Grace Period
  addons/airway/XEH_preInit.sqf
  addons/airway/functions/fnc_handleAirway.sqf
  addons/airway/functions/fnc_handlePuking.sqf
  addons/airway/functions/fnc_init.sqf
  addons/airway/functions/fnc_treatmentAdvanced_AccuvacLocal.sqf
  addons/airway/functions/fnc_treatmentAdvanced_turnaroundHead.sqf
  addons/airway/stringtable.xml
  addons/misc/functions/fnc_fullHealLocal.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
Labels: kind/feature request

#401 Airway - Make Head Turning Continuous
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/CfgMoves.hpp
  addons/airway/XEH_PREP.hpp
  addons/airway/XEH_preInit.sqf
  addons/airway/config.cpp
  addons/airway/functions/fnc_startHeadTurning.sqf
  addons/airway/functions/fnc_treatmentAdvanced_turnaroundHead.sqf
  addons/airway/stringtable.xml
Labels: kind/feature request

#399 Circulation - Add cardiac arrest bleed rate setting
  addons/circulation/XEH_preInit.sqf
  addons/circulation/stringtable.xml
  addons/pharma/functions/fnc_getBloodLoss.sqf
Labels: kind/feature request

#400 Breathing - Improve Check Breathing action
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/XEH_PREP.hpp
  addons/breathing/functions/fnc_checkBreathing.sqf
  addons/breathing/stringtable.xml
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/XEH_PREP.hpp
  addons/pharma/functions/fnc_inspectBreath.sqf
  addons/pharma/stringtable.xml
  addons/surgery/XEH_preInit.sqf
Labels: kind/enhancement

#402 Bump version for v2.12.3 DEV Update
  addons/main/script_version.hpp
Labels: ignore changelog

#403 Translation - Improve Japanese for 2.13
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#406 GUI - Add Airway & Pharmacy medical menu visuals
  addons/gui/data/body_image/head_guedeltube.paa
  addons/gui/data/body_image/head_kinglt.paa
  addons/gui/data/body_image/leftarm_iv.paa
  addons/gui/data/body_image/leftleg_iv.paa
  addons/gui/data/body_image/rightarm_iv.paa
  addons/gui/data/body_image/rightleg_iv.paa
  addons/gui/data/body_image/torso_io.paa
  addons/gui/functions/fnc_updateBodyImage.sqf
  addons/gui/gui.hpp
  addons/gui/script_component.hpp
Labels: kind/feature request

#408 Translation - Fix and Revert \n(space) changes.
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations
