Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-09, with the labels that each got.

#409 Circulation/GUI - Make Vitals Monitoring display pulse rate
  addons/airway/XEH_preInit.sqf
  addons/airway/functions/fnc_handlePuking.sqf
  addons/airway/stringtable.xml
  addons/breathing/XEH_preInit.sqf
  addons/breathing/stringtable.xml
  addons/circulation/CfgVehicles.hpp
  addons/circulation/XEH_preInit.sqf
  addons/circulation/defines.hpp
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
  addons/circulation/functions/fnc_AED_Charge.sqf
  addons/circulation/sounds/checkpulse_nopulsepushanalyze.wav
  addons/circulation/sounds/pushanalyze.wav
  addons/circulation/sounds/pushtoshock.wav
  addons/circulation/sounds/standclear_pushtoshock.wav
  addons/circulation/stringtable.xml
  addons/circulation/ui/AEDX_Monitor_Dialog.hpp
  addons/gui/XEH_preInit.sqf
  addons/gui/functions/fnc_updateLogList.sqf
  addons/gui/stringtable.xml
  addons/misc/XEH_preInit.sqf
  addons/misc/stringtable.xml
  addons/pharma/XEH_preInit.sqf
  addons/surgery/stringtable.xml
Labels: kind/feature request

#411 Airway - Add recovery position pose
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/CfgMoves.hpp
  addons/airway/anim/recovery_position.rtm
  addons/airway/functions/fnc_treatmentAdvanced_CancelRecoveryPosition.sqf
  addons/airway/functions/fnc_treatmentAdvanced_RecoveryPosition.sqf
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
Labels: kind/feature request

#412 Zeus - Add module to prevent instant AI death
  addons/main/script_macros.hpp
  addons/misc/CfgFunctions.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/functions/fnc_conditionExecutionDeath.sqf
  addons/misc/functions/fnc_conditionSecondChance.sqf
  addons/zeus/CfgVehicles.hpp
  addons/zeus/XEH_PREP.hpp
  addons/zeus/config.cpp
  addons/zeus/functions/fnc_openMedicalMenu.sqf
  addons/zeus/functions/fnc_toggleAIDeathModule.sqf
  addons/zeus/functions/fnc_ui_changeBloodType.sqf
  addons/zeus/functions/fnc_ui_changeCardiacState.sqf
  addons/zeus/functions/fnc_ui_manageAirway.sqf
  addons/zeus/stringtable.xml
  addons/zeus/ui/Icon_Module_Zeus_Prevent_AI_Death.paa
Labels: kind/feature request

#414 Translate - Add french translate
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#410 misc - Fix PPeffect error on server at fullHealLocal
  addons/misc/functions/fnc_fullHealLocal.sqf
Labels: kind/bug fix
