Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-05, with the labels that each got.

#300 Circulation - Fix: Assign proper bloodtype to other players
  addons/circulation/functions/fnc_bloodType.sqf
Labels: kind/enhancement

#305 Spanish translation
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#303 Pharma - Fix: Style and missing parameter in txa treatment
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/CfgMagazines.hpp
  addons/pharma/functions/fnc_treatmentAdvanced_TXA.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_TXALocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_medicationLocal.sqf
Labels: kind/bug fix

#292 Translations - Add missing Polish
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#302 Airway - Add: New guedel tube picture
  addons/airway/ui/guedel_normal.paa
Labels: kind/enhancement

#306 Tools - Add release-drafter
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ignore changelog

#297 Airway - KingLT & Guedeltubus remove option
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/XEH_PREP.hpp
  addons/airway/XEH_postInit.sqf
  addons/airway/XEH_preInit.sqf
  addons/airway/functions/fnc_treatmentAdvanced_RemoveAirwayItem.sqf
  addons/airway/functions/fnc_treatmentAdvanced_RemoveAirwayItemLocal.sqf
  addons/airway/functions/fnc_treatmentAdvanced_airwayLocal.sqf
  addons/airway/stringtable.xml
Labels: kind/feature request

#307 Tools - Update for wrong parameter in release-drafter
  .github/workflows/release-drafter.yml
Labels: ignore changelog

#283 Circulation - Change for meds calculations during CPR
  addons/circulation/functions/fnc_cprLocal.sqf
Labels: kind/enhancement

#312 Airway - Change obstruction default chance
  addons/airway/XEH_preInit.sqf
  addons/airway/functions/fnc_treatmentAdvanced_CancelRecoveryPositionLocal.sqf
  addons/airway/stringtable.xml
Labels: area/compatibility

#310 Surgery - Change Surgical Action Medical Requirements
  addons/surgery/ACE_Medical_Treatment_Actions.hpp
  addons/surgery/XEH_preInit.sqf
  addons/surgery/functions/fnc_npwtTreatmentLocal.sqf
  addons/surgery/stringtable.xml
Labels: area/compatibility

#317 Translations - Add Czech Translation
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#321 Pharma - Fix - Ketamine, Fentanyl & Pervitin PP fix
  addons/pharma/functions/fnc_fentanylPP.sqf
  addons/pharma/functions/fnc_ketaminePP.sqf
  addons/pharma/functions/fnc_pervitinPP.sqf
Labels: kind/bug fix

#322 Tools - Fix github workflow
  .github/workflows/release-drafter.yml
Labels: ignore changelog

#309 Tools - Add translations issue
  .github/workflows/arma.yml
  tools/deploy.py
  tools/stringtablediag.py
Labels: ignore changelog

#318 Airway - Improve auto-triage on blocked airways
  addons/airway/XEH_preInit.sqf
  addons/airway/functions/fnc_checkAirway.sqf
  addons/airway/stringtable.xml
  addons/gui/gui.hpp
Labels: kind/enhancement

#319 Translations - Improve Spanish
  addons/airway/stringtable.xml
  addons/chemical/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#324 Tools - Fix translation issue
  .github/workflows/arma.yml
  .github/workflows/documentation.yml
Labels: ignore changelog

#316 Translations - Add missing Japanese.
  addons/airway/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#327 Airway - Change Reverting default obstruction chance
  addons/airway/XEH_preInit.sqf
Labels: ignore changelog

#328 Tools - Add auto-upload workflow for release
  .editorconfig
  .github/workflows/documentation.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: ignore changelog

#329 Bump version for release
  addons/main/script_version.hpp
Labels: ignore changelog
