Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-06, with the labels that each got.

#331 Airway/Surgery - Add missing french translations
  addons/airway/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#332 Tools - Fix documentation workflow
  .github/workflows/documentation.yml
Labels: ignore changelog

#314 Chemical - Improve code style
  addons/airway/functions/fnc_updateInjuryList.sqf
  addons/breathing/functions/fnc_fullHealLocal.sqf
  addons/chemical/CfgAmmo.hpp
  addons/chemical/CfgCloudlets.hpp
  addons/chemical/CfgVehicles.hpp
  addons/chemical/XEH_PREP.hpp
  addons/chemical/XEH_postInit.sqf
  addons/chemical/functions/fnc_AttributeRadius.sqf
  addons/chemical/functions/fnc_CASCreateGas.sqf
  addons/chemical/functions/fnc_addLoadAction.sqf
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_breathing.sqf
  addons/chemical/functions/fnc_canPutGasMask.sqf
  addons/chemical/functions/fnc_checkGasMaskDur.sqf
  addons/chemical/functions/fnc_chemDetector.sqf
  addons/chemical/functions/fnc_coughing.sqf
  addons/chemical/functions/fnc_createSealAction.sqf
  addons/chemical/functions/fnc_createZone.sqf
  addons/chemical/functions/fnc_displayGasMaskDur.sqf
  addons/chemical/functions/fnc_gasAI.sqf
  addons/chemical/functions/fnc_gasCheck.sqf
  addons/chemical/functions/fnc_gasmodule.sqf
  addons/chemical/functions/fnc_getChemDetectorState.sqf
  addons/chemical/functions/fnc_getList.sqf
  addons/chemical/functions/fnc_giveUnitGasMask.sqf
  addons/chemical/functions/fnc_handleCSGas.sqf
  addons/chemical/functions/fnc_handleFired.sqf
  addons/chemical/functions/fnc_handleGasMaskDur.sqf
  addons/chemical/functions/fnc_init.sqf
  addons/chemical/functions/fnc_spawnSmoke.sqf
  addons/chemical/functions/fnc_throwGrenade.sqf
  addons/chemical/functions/fnc_ui_gasModule.sqf
  addons/chemical/functions/fnc_updateBodyImage.sqf
  addons/chemical/stringtable.xml
  addons/chemical/ui/RscAttributes.hpp
  addons/misc/functions/fnc_handleRespawn.sqf
Labels: kind/cleanup

#333 Circulation - Fix wrong language string for AED-X SpO2 warning
  addons/circulation/XEH_preInit.sqf
  addons/circulation/stringtable.xml
Labels: kind/cleanup

#339 Circulation - Fix missing event in treatment fnc
  addons/circulation/functions/fnc_treatment.sqf
Labels: kind/bug fix

#343 Tools - Fix files for release workflow
  .github/workflows/release.yml
Labels: ignore changelog

#341 Pharma | Fix | Medical Action abort bug fix
  addons/breathing/functions/fnc_fullHealLocal.sqf
  addons/breathing/functions/fnc_handleBreathing.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
  addons/pharma/XEH_postInit.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_PervitinLocal.sqf
Labels: kind/bug fix

#334 Breathing - Fix stethoscope sounds looping
  addons/breathing/functions/fnc_listenLungs.sqf
Labels: kind/bug fix

#335 Circulation - Fix player chosen blood type not applying properly
  addons/circulation/XEH_postInit.sqf
  addons/circulation/XEH_preInit.sqf
  addons/circulation/functions/fnc_generateBloodType.sqf
Labels: kind/bug fix

#344 Circulation - Fix internal bleeding persisting after respawn
  addons/misc/functions/fnc_handleRespawn.sqf
Labels: kind/bug fix

#337 Breathing - Add setting to set what locations provide oxygen
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/CfgVehicles.hpp
  addons/breathing/XEH_preInit.sqf
  addons/breathing/stringtable.xml
Labels: kind/enhancement

#346 Github - Add workflow for dev updates
  .github/workflows/dev.yml
Labels: ignore changelog

#330 Breathing - Fix - SpO2 loss not decreasing
  addons/breathing/functions/fnc_handleBreathing.sqf
Labels: kind/bug fix

#320 Misc - Add - Armbands
  addons/misc/CfgGlasses.hpp
  addons/misc/CfgVehicles.hpp
  addons/misc/CfgWeapons.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_postInit.sqf
  addons/misc/XEH_preInit.sqf
  addons/misc/config.cpp
  addons/misc/functions/fnc_actionLowerBy10.sqf
  addons/misc/functions/fnc_addActionRaise.sqf
  addons/misc/functions/fnc_checkArmbandCondition.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
  addons/misc/functions/fnc_heliAddActionDeploy.sqf
  addons/misc/functions/fnc_init.sqf
  addons/misc/functions/fnc_slingArmband.sqf
  addons/misc/functions/fnc_stringToArray.sqf
  addons/misc/functions/fnc_unSlingArmband.sqf
  addons/misc/models/armband/Armband.p3d
  addons/misc/models/armband/ArmbandKAT.paa
  addons/misc/models/armband/ArmbandWC.paa
  addons/misc/models/armband/ArmbandWCD.paa
  addons/misc/models/armband/ArmbandWCM.paa
  addons/misc/models/armband/model.cfg
  addons/misc/stringtable.xml
  addons/misc/ui/ArmbandKat.paa
  addons/misc/ui/ArmbandLeftArm.paa
  addons/misc/ui/ArmbandLeftLeg.paa
  addons/misc/ui/ArmbandRightArm.paa
  addons/misc/ui/ArmbandRightLeg.paa
  addons/misc/ui/ArmbandWhiteCross.paa
  addons/misc/ui/ArmbandWhiteCrossDoctor.paa
  addons/misc/ui/ArmbandWhiteCrossMedic.paa
  addons/misc/ui/downarrow.paa
  addons/misc/ui/fliparrow.paa
  addons/misc/ui/stretcher.paa
  addons/misc/ui/uparrow.paa
Labels: kind/feature request

#336 Chemical - Fix gas mask action visibility on dedicated server
  addons/chemical/XEH_postInit.sqf
  addons/chemical/XEH_preInit.sqf
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_breathing.sqf
  addons/chemical/functions/fnc_canPutGasMask.sqf
  addons/chemical/functions/fnc_canReplaceFilter.sqf
  addons/chemical/functions/fnc_gasAI.sqf
  addons/chemical/functions/fnc_giveUnitGasMask.sqf
  addons/chemical/functions/fnc_handleCSGas.sqf
  addons/chemical/functions/fnc_handleGasMaskDur.sqf
  addons/chemical/functions/fnc_hasGasMaskON.sqf
  addons/chemical/functions/fnc_hasGasmask.sqf
  addons/chemical/functions/fnc_init.sqf
Labels: kind/bug fix, tested

#345 Chemical - Fix Virtual Zeus and units with damage turned off being killed by Chemical
  addons/chemical/XEH_PREP.hpp
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_clearChemicalInjuriesLocal.sqf
  addons/chemical/functions/fnc_gasAI.sqf
  addons/chemical/functions/fnc_gasCheck.sqf
  addons/chemical/functions/fnc_gasCheckLocal.sqf
  addons/chemical/functions/fnc_handleCSGas.sqf
Labels: kind/bug fix, tested

#347 Chemical - Fix gas handling
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_gasCheckLocal.sqf
  addons/chemical/functions/fnc_handleCSGas.sqf
Labels: kind/bug fix

#340 Misc - Add setting to share vehicle stored medical equipment
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/functions/fnc_hasOxygenTank.sqf
  addons/breathing/functions/fnc_useBVM.sqf
  addons/breathing/stringtable.xml
  addons/circulation/CfgFunctions.hpp
  addons/circulation/functions/fnc_treatment.sqf
  addons/misc/CfgFunctions.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_preInit.sqf
  addons/misc/functions/fnc_getUniqueItems.sqf
  addons/misc/functions/fnc_hasItem.sqf
  addons/misc/functions/fnc_removeItemFromVehicle.sqf
  addons/misc/functions/fnc_useItem.sqf
  addons/misc/stringtable.xml
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/functions/fnc_treatmentAdvanced_Caffeine.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_Carbonate.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_Painkillers.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_Pervitin.sqf
Labels: kind/feature request

#349 Chemical - Fix GasMaks selfinteractions are now displayed
  addons/chemical/XEH_postInit.sqf
  addons/chemical/XEH_preInit.sqf
Labels: kind/bug fix

#348 Airway - Fix airway item persisting after respawn
  addons/airway/functions/fnc_init.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
Labels: kind/bug fix

#351 Misc | Add | Blood Group Patches
  addons/misc/CfgBloodGroupsInsignia.hpp
  addons/misc/config.cpp
  addons/misc/stringtable.xml
  addons/misc/ui/BloodGroupPatches/0_Neg_Red.paa
  addons/misc/ui/BloodGroupPatches/0_Pos_Red.paa
  addons/misc/ui/BloodGroupPatches/AB_Neg_Red.paa
  addons/misc/ui/BloodGroupPatches/AB_Pos_Red.paa
  addons/misc/ui/BloodGroupPatches/A_Neg_Red.paa
  addons/misc/ui/BloodGroupPatches/A_Pos_Red.paa
  addons/misc/ui/BloodGroupPatches/B_Neg_Red.paa
  addons/misc/ui/BloodGroupPatches/B_Pos_Red.paa
Labels: kind/feature request, tested

#352 Misc | Add | Bubble Wrap
  addons/misc/CfgMagazines.hpp
  addons/misc/CfgSounds.hpp
  addons/misc/CfgVehicles.hpp
  addons/misc/CfgWeapons.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_postInit.sqf
  addons/misc/XEH_preInit.sqf
  addons/misc/config.cpp
  addons/misc/functions/fnc_BubbleWrap.sqf
  addons/misc/sounds/bubble_wrap_1.ogg
  addons/misc/sounds/bubble_wrap_2.ogg
  addons/misc/sounds/bubble_wrap_3.ogg
  addons/misc/sounds/bubble_wrap_4.ogg
  addons/misc/sounds/bubble_wrap_5.ogg
  addons/misc/stringtable.xml
  addons/misc/ui/Bubble_Wrap_Interaction.paa
  addons/misc/ui/Bubble_Wrap_Item.paa
  addons/pharma/ACE_Medical_Treatment.hpp
Labels: kind/feature request, tested

#353 Misc - Fix missing class declaration
  addons/misc/CfgWeapons.hpp
Labels: ignore changelog, kind/bug fix

#357 Airway - Add option to disable head turning or overstretch when airway item is inserted
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/XEH_preInit.sqf
  addons/airway/stringtable.xml
Labels: kind/feature request, tested

#355 Translation | Addition/Improvment | German
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#356 Chemical - Fix - Chemical Detector
  addons/chemical/XEH_postInit.sqf
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_chemDetector.sqf
  addons/chemical/functions/fnc_gasCheckLocal.sqf
  addons/chemical/functions/fnc_init.sqf
Labels: kind/bug fix, in-tests

#358 Main - Update version for dev release
  addons/main/script_version.hpp
Labels: ignore changelog

#360 Translation - Add/Improve Japanese stringtable
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#362 Translation - Add missing french stringtable
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#359 Translations - Add missing Korean
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#364 Translation | Add | Missing German Translations
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
Labels: area/translations
