Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-12, with the labels that each got.

#444 Airway/Breathing/Circulation/Surgery/Misc - Various fixes
  addons/airway/functions/fnc_startHeadTurning.sqf
  addons/airway/stringtable.xml
  addons/breathing/functions/fnc_useBVM.sqf
  addons/breathing/stringtable.xml
  addons/chemical/functions/fnc_gasAI.sqf
  addons/circulation/XEH_postInit.sqf
  addons/circulation/functions/fnc_AED_Shock.sqf
  addons/circulation/functions/fnc_CPRStart.sqf
  addons/circulation/functions/fnc_cprLocal.sqf
  addons/circulation/functions/fnc_handleCardiacArrest.sqf
  addons/circulation/functions/fnc_placeAED.sqf
  addons/circulation/stringtable.xml
  addons/misc/functions/fnc_FAK_unpack.sqf
  addons/surgery/XEH_preInit.sqf
  addons/surgery/functions/fnc_incisionLocal.sqf
  addons/surgery/stringtable.xml
Labels: kind/bug fix

#446 Misc - Add tourniquet side effects
  addons/misc/CfgFunctions.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_postInit.sqf
  addons/misc/XEH_preInit.sqf
  addons/misc/functions/fnc_fullHealLocal.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
  addons/misc/functions/fnc_handleTourniquetEffects.sqf
  addons/misc/functions/fnc_updateDamageEffects.sqf
  addons/misc/script_component.hpp
  addons/misc/stringtable.xml
  addons/pharma/XEH_PREP.hpp
Labels: kind/feature request

#445 Airway - Change recovery position & reword check airway hints
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/XEH_PREP.hpp
  addons/airway/XEH_postInit.sqf
  addons/airway/XEH_preInit.sqf
  addons/airway/functions/fnc_checkAirway.sqf
  addons/airway/functions/fnc_handleRecoveryPosition.sqf
  addons/airway/functions/fnc_treatmentAdvanced_CancelRecoveryPosition.sqf
  addons/airway/functions/fnc_treatmentAdvanced_CancelRecoveryPositionLocal.sqf
  addons/airway/functions/fnc_treatmentAdvanced_RecoveryPosition.sqf
  addons/airway/functions/fnc_treatmentAdvanced_RecoveryPositionLocal.sqf
  addons/airway/functions/fnc_treatmentAdvanced_airwayLocal.sqf
  addons/airway/functions/fnc_treatmentAdvanced_hyperextendHead.sqf
  addons/airway/stringtable.xml
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/functions/fnc_canUseBVM.sqf
  addons/breathing/functions/fnc_lowSpO2pp.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_tensionpneumothorax.sqf
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/functions/fnc_AEDXPlaced_CheckCondition.sqf
  addons/circulation/functions/fnc_Defibrillator_CheckCondition.sqf
  addons/circulation/functions/fnc_Defibrillator_Pads_CheckCondition.sqf
  addons/gui/functions/fnc_updateInjuryList.sqf
  addons/misc/functions/fnc_treatmentSuccess.sqf
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/zeus/stringtable.xml
Labels: kind/enhancement

#449 Circulation - Fix blood poisoning not causing cardiac arrest
  addons/circulation/XEH_postInit.sqf
  addons/circulation/functions/fnc_treatmentAdvanced_IV.sqf
Labels: kind/bug fix

#448 Circulation - AED fixes
  addons/circulation/functions/fnc_AEDXPlaced_CheckCondition.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_AEDX_VitalsMonitor_CheckCondition.sqf
  addons/circulation/functions/fnc_Defibrillator_Pads_CheckCondition.sqf
  addons/circulation/stringtable.xml
  addons/circulation/ui/AEDX_Monitor_Dialog.hpp
Labels: kind/bug fix

#443 Translation - Improve Japanese for 2.13.3
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#454 Airway - Norwegian translation update
  AUTHORS.txt
  addons/airway/stringtable.xml
Labels: area/translations

#450 Breathing - Add BVM and O2Tank to Supply Crates
  addons/breathing/CfgMagazines.hpp
  addons/breathing/CfgVehicles.hpp
  addons/breathing/CfgWeapons.hpp
Labels: kind/feature request
