Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-04, with the labels that each got.

#294 Complete German Translation 20/4/23
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#295 Breathing - Fix for BVM Time
  addons/breathing/XEH_preInit.sqf
Labels: kind/bug fix

#285 Fix for COMPILE
  addons/airway/CfgEventHandlers.hpp
  addons/airway/XEH_init.sqf
  addons/airway/functions/fnc_init.sqf
  addons/breathing/CfgEventHandlers.hpp
  addons/breathing/XEH_init.sqf
  addons/breathing/functions/fnc_init.sqf
  addons/chemical/CfgEventHandlers.hpp
  addons/chemical/XEH_init.sqf
  addons/chemical/functions/fnc_init.sqf
  addons/circulation/CfgEventHandlers.hpp
  addons/circulation/XEH_init.sqf
  addons/circulation/functions/fnc_init.sqf
  addons/misc/CfgEventHandlers.hpp
  addons/misc/XEH_init.sqf
  addons/misc/functions/fnc_init.sqf
  addons/pharma/CfgEventHandlers.hpp
  addons/pharma/XEH_init.sqf
  addons/pharma/functions/fnc_init.sqf
  addons/surgery/CfgEventHandlers.hpp
  addons/surgery/XEH_init.sqf
  addons/surgery/functions/fnc_init.sqf
Labels: kind/optimization
