Repository KAT-Advanced-Medical/KAM, pull requests merged in 2023-07, with the labels that each got.

#361 Misc - Fix shared vehicle equipment "except self-treatment" setting
  addons/misc/functions/fnc_removeItemFromVehicle.sqf
  addons/misc/functions/fnc_useItem.sqf
Labels: kind/bug fix, tested

#366 Chemical - Fix Zeus module UI + unlocalized string
  addons/chemical/functions/fnc_AttributeRadius.sqf
  addons/chemical/functions/fnc_ui_gasModule.sqf
  addons/chemical/ui/RscAttributes.hpp
Labels: kind/cleanup, tested

#369 Translations - Update to 100% italian
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#372 Translations - Add Spanish translation to new content
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#371 Surgery - Add Additional Settings to Allow Patient to Remain Awake During Surgeries
  addons/surgery/XEH_preInit.sqf
  addons/surgery/functions/fnc_incisionLocal.sqf
  addons/surgery/functions/fnc_openReductionLocal.sqf
  addons/surgery/functions/fnc_openReductionProgressLocal.sqf
  addons/surgery/stringtable.xml
Labels: kind/enhancement, tested
