Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-03, with the labels that each got.

#476 Airway / Circulation - Improve - Activity Logs
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/functions/fnc_checkAirway.sqf
  addons/airway/functions/fnc_treatmentAdvanced_Accuvac.sqf
  addons/airway/functions/fnc_treatmentAdvanced_hyperextendHead.sqf
  addons/airway/stringtable.xml
  addons/breathing/functions/fnc_checkBreathing.sqf
  addons/breathing/functions/fnc_inspectChest.sqf
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/XEH_PREP.hpp
  addons/circulation/XEH_preInit.sqf
  addons/circulation/functions/fnc_bloodTypeLog.sqf
  addons/circulation/stringtable.xml
  addons/misc/functions/fnc_getDogtagData.sqf
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/zeus/functions/fnc_ui_changeBloodType.sqf
  addons/zeus/ui/RscAttributes.hpp
Labels: kind/optimization

#456 Misc - Fix excessive FAK items are dropped on floor as single items
  addons/misc/functions/fnc_FAK_unpack.sqf
Labels: kind/bug fix, status/tested

#485 Breathing / Circulation / Misc - Fix - Exceptions not being set correctly
  addons/breathing/CfgVehicles.hpp
  addons/circulation/CfgVehicles.hpp
  addons/misc/CfgVehicles.hpp
Labels: kind/bug fix

#487 Translation - Improve Japanese for later 2.13.4
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/misc/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#473 Circulation - Fix / Add - Blood drawing check not working when overweight / Pharma IV requirement check
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/functions/fnc_canDraw.sqf
  addons/circulation/functions/fnc_drawBlood.sqf
  addons/pharma/XEH_preInit.sqf
  addons/pharma/stringtable.xml
Labels: kind/bug fix

#490 Translation - Improve Japanese for later 2.14.0rc1
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/pharma/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#501 Pharmacy/Surgery - Change the IO painkiller checks and change the closed reduction checks
  addons/pharma/functions/fnc_applyIV.sqf
  addons/surgery/functions/fnc_closedReductionLocal.sqf
Labels: kind/enhancement

#504 Translate - Russian
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations
