Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-06, with the labels that each got.

#543 Misc/GUI - Fix error on bandaging
  addons/gui/CfgFunctions.hpp
  addons/gui/functions/fnc_menuPFH.sqf
  addons/misc/functions/fnc_treatment.sqf
  addons/misc/functions/fnc_treatmentSuccess.sqf
  addons/misc/functions/fnc_useItem.sqf
Labels: kind/bug fix

#544 Pharma - Fix coagulation bug
  addons/pharma/functions/fnc_handleRespawn.sqf
Labels: kind/bug fix

#547 Translation - Improve French (not the people)
  addons/circulation/stringtable.xml
Labels: area/translations

#549 Pharma - Adjust magazine items to use ace system
  addons/pharma/CfgMagazines.hpp
  addons/pharma/CfgWeapons.hpp
  addons/pharma/XEH_postInit.sqf
Labels: kind/enhancement

#548 Pharma - Change KAM Painkillers to CWMP
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/CfgMagazines.hpp
  addons/pharma/XEH_PREP.hpp
  addons/pharma/functions/fnc_treatmentAdvanced_CWMP.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_Carbonate.sqf
  addons/pharma/stringtable.xml
  addons/pharma/ui/icon_painkillers.paa
Labels: area/compatibility
