Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-08, with the labels that each got.

#573 Breathing - Fix Pulse Oximeter item description in inventory
  addons/breathing/CfgVehicles.hpp
  addons/breathing/CfgWeapons.hpp
  addons/breathing/functions/fnc_gui_updateInjuryListPart.sqf
  addons/breathing/stringtable.xml
Labels: kind/enhancement

#575 Pharma - Improve - Coagulation improvements and a fix for phenyl autoinjector
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/XEH_preInit.sqf
  addons/pharma/functions/fnc_clotWound.sqf
  addons/pharma/functions/fnc_coagRegen.sqf
  addons/pharma/functions/fnc_fluidLocal.sqf
  addons/pharma/functions/fnc_fullHealLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_CheckCoag.sqf
  addons/surgery/ACE_Medical_Treatment.hpp
Labels: kind/enhancement

#576 Pharma- Fix Coag PR 575
  addons/surgery/ACE_Medical_Treatment.hpp
Labels: kind/cleanup

#577 Surgery - Add settings for REBOA / Pericardial Tap / Ultrasound
  addons/surgery/ACE_Medical_Treatment_Actions.hpp
  addons/surgery/XEH_preInit.sqf
  addons/surgery/stringtable.xml
Labels: kind/enhancement

#568 PHARMA - Add IV epinephrine with stronger effects then autoinjector epi
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/CfgWeapons.hpp
  addons/pharma/XEH_preInit.sqf
  addons/pharma/config.cpp
  addons/pharma/functions/fnc_medicationLocal.sqf
  addons/pharma/stringtable.xml
  addons/pharma/ui/icon_EpinephrineIV.paa
Labels: kind/feature request

#570 Translation - Improve Portuguese
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#579 Pharma, Misc - Fix missing translation entry
  addons/misc/CfgVehicles.hpp
  addons/pharma/stringtable.xml
Labels: ignore changelog, kind/bug fix

#574 Pharma - Improve item descriptions on inventory
  addons/pharma/stringtable.xml
Labels: area/translations

#581 Translation - Improve Japanese
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#582 Chemical - Fix Zones not working (again)
  addons/chemical/functions/fnc_gasmodule.sqf
Labels: kind/bug fix

#572 Translations - Add Spanish
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/pharma/stringtable.xml
Labels: area/translations

#583 Surgery - Reboa/Surgery Fix
  addons/surgery/XEH_PREP.hpp
  addons/surgery/XEH_postInit.sqf
Labels: kind/bug fix

#580 Misc - Fix FAKs not showing up inside vehicles
  addons/misc/CfgVehicles.hpp
Labels: kind/bug fix

#584 Surgery - Change EACA and TXA Default Value
  addons/pharma/XEH_preInit.sqf
Labels: kind/enhancement

#587 Translation - Add|Fix - Coagulation translation/typo
  addons/breathing/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#585 Pharma - Improve IV Epinephrine
  addons/circulation/functions/fnc_cprLocal.sqf
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/functions/fnc_handleRespawn.sqf
  addons/pharma/functions/fnc_init.sqf
Labels: kind/bug fix

#586 Pharma - Fix - Coagsense Location settings
  addons/pharma/XEH_preInit.sqf
Labels: kind/bug fix

#578 Watch - Add KATMIN Exercise Watch
  addons/watch/$PBOPREFIX$
  addons/watch/CfgEventHandlers.hpp
  addons/watch/CfgWeapons.hpp
  addons/watch/RscTitles.hpp
  addons/watch/UI/watch_icon.paa
  addons/watch/UI/watch_katmin.paa
  addons/watch/UI/watch_katmin_direction.paa
  addons/watch/UI/watch_overcast.paa
  addons/watch/UI/watch_rain.paa
  addons/watch/UI/watch_sun.paa
  addons/watch/XEH_PREP.hpp
  addons/watch/XEH_postInit.sqf
  addons/watch/XEH_preInit.sqf
  addons/watch/config.cpp
  addons/watch/functions/fnc_hideKWatch.sqf
  addons/watch/functions/fnc_showKWatch.sqf
  addons/watch/script_component.hpp
  addons/watch/stringtable.xml
Labels: kind/feature request

#590 Zeus - Fix changeBloodType
  addons/zeus/functions/fnc_ui_changeBloodType.sqf
Labels: kind/bug fix
