Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-07, with the labels that each got.

#554 Chemical/Misc/Surgery/Pharma - Fix Hashmap retrieval, inheritance and CWMP issues
  addons/chemical/CfgVehicles.hpp
  addons/misc/CfgVehicles.hpp
  addons/misc/functions/fnc_treatment.sqf
  addons/misc/vehicle_stretcher.hpp
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/surgery/ACE_Medical_Treatment_Actions.hpp
Labels: kind/bug fix

#556 Misc - Fix IFAK unpacking causing crash
  addons/misc/functions/fnc_FAK_unpack.sqf
Labels: kind/cleanup

#557 Chemical/Misc/Surgery/Pharma - Fix Hashmap retrieval, inheritance and CWMP issues
  addons/chemical/CfgVehicles.hpp
  addons/chemical/functions/fnc_ui_gasModule.sqf
  addons/misc/CfgVehicles.hpp
  addons/misc/vehicle_stretcher.hpp
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/surgery/ACE_Medical_Treatment_Actions.hpp
  addons/zeus/functions/fnc_ui_changeBloodType.sqf
  addons/zeus/functions/fnc_ui_changeCardiacState.sqf
  addons/zeus/functions/fnc_ui_manageAirway.sqf
Labels: kind/cleanup

#558 Translations - Spanish
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#559 Misc - Fix kat_stretcher not supporting CBA XEH
  addons/misc/CfgVehicles.hpp
Labels: kind/cleanup

#561 Circulation - Fix AED pads
  addons/circulation/functions/fnc_Defibrillator_AttachPads.sqf
  addons/circulation/functions/fnc_Defibrillator_RemovePads.sqf
Labels: kind/bug fix

#563 Translations - Add & Improve Portuguese
  addons/breathing/stringtable.xml
Labels: area/translations

#565 Pharma - Fix CoagSense displaying wrong message with changed default value
  addons/pharma/functions/fnc_treatmentAdvanced_CheckCoag.sqf
  addons/pharma/stringtable.xml
Labels: ignore changelog, kind/bug fix

#566 Breathing/Misc - Adjust magazine items to use ace system
  addons/breathing/CfgMagazines.hpp
  addons/breathing/CfgWeapons.hpp
  addons/breathing/XEH_postInit.sqf
  addons/misc/CfgMagazines.hpp
  addons/misc/CfgWeapons.hpp
  addons/misc/XEH_postInit.sqf
  addons/misc/functions/fnc_BubbleWrap.sqf
Labels: kind/enhancement

#569 GUI - Fix wrong diplay of qualitative description of the rate of bleeding
  addons/gui/functions/fnc_updateInjuryList.sqf
  addons/main/script_macros.hpp
Labels: kind/bug fix

#567 Pharma - Remove neck tourniquet feature
  addons/misc/ACE_Medical_Treatment_Actions.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_postInit.sqf
  addons/misc/XEH_preInit.sqf
  addons/misc/functions/fnc_headTourniquet.sqf
  addons/misc/functions/fnc_headTourniquetLocal.sqf
  addons/misc/stringtable.xml
Labels: kind/enhancement
