Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-02, with the labels that each got.

#469 Misc - Add default meta.cpp for Steam Workshop association
  meta.cpp
Labels: kind/feature request, area/compatibility

#479 Chemical/Circulation/GUI/Misc/Pharmacy - Apply HEMTT suggestions
  addons/chemical/functions/fnc_clearChemicalInjuriesLocal.sqf
  addons/chemical/functions/fnc_getChemDetectorState.sqf
  addons/chemical/functions/fnc_hasGasmask.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
  addons/circulation/functions/fnc_CPRStart.sqf
  addons/gui/functions/fnc_countTreatmentItems.sqf
  addons/misc/functions/fnc_fullHealLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_FlushLocal.sqf
Labels: kind/optimization

#481 Circulation - Fix AED/X station interactions
  addons/circulation/CfgVehicles.hpp
  addons/circulation/XEH_PREP.hpp
  addons/circulation/XEH_postInit.sqf
  addons/circulation/XEH_preInit.sqf
  addons/circulation/functions/fnc_DefibrillatorPlaced_CheckCondition.sqf
  addons/circulation/functions/fnc_placeAED.sqf
  addons/circulation/functions/fnc_placeAED_PickUpAction.sqf
  addons/circulation/stringtable.xml
Labels: kind/bug fix

#484 Zeus - Add checkbox to module for deteriorating pneumothorax
  addons/breathing/XEH_PREP.hpp
  addons/breathing/functions/fnc_handleBreathing.sqf
  addons/breathing/functions/fnc_handlePneumothoraxDeterioration.sqf
  addons/breathing/functions/fnc_handlePulmoHit.sqf
  addons/breathing/functions/fnc_inflictAdvancedPneumothorax.sqf
  addons/circulation/functions/fnc_updateBloodPressureChange.sqf
  addons/zeus/functions/fnc_ui_manageAirway.sqf
  addons/zeus/stringtable.xml
  addons/zeus/ui/RscAttributes.hpp
Labels: kind/feature request

#462 Misc - Add / Change - FAK pack list & modify FAK strings
  addons/misc/CfgVehicles.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_preInit.sqf
  addons/misc/functions/fnc_FAK_displayContent.sqf
  addons/misc/functions/fnc_FAK_updateContents.sqf
  addons/misc/stringtable.xml
  addons/misc/ui/AFAK_DisplayItems.paa
  addons/misc/ui/IFAK_DisplayItems.paa
  addons/misc/ui/MFAK_DisplayItems.paa
Labels: kind/enhancement

#463 Misc - Add / Update - Armband NVG version integration & code cleanup
  addons/misc/CfgGlasses.hpp
  addons/misc/CfgVehicles.hpp
  addons/misc/CfgWeapons.hpp
  addons/misc/XEH_postInit.sqf
  addons/misc/XEH_preInit.sqf
  addons/misc/functions/fnc_checkArmbandCondition.sqf
  addons/misc/functions/fnc_slingArmband.sqf
  addons/misc/functions/fnc_unSlingArmband.sqf
Labels: kind/cleanup, kind/optimization

#468 Misc - Add - Unpack other players FAK if unconscious
  addons/misc/CfgVehicles.hpp
Labels: kind/feature request

#475 Surgery - Fix - Vacuum Dressing deleted location & medlvl
  addons/surgery/ACE_Medical_Treatment_Actions.hpp
  addons/surgery/XEH_preInit.sqf
  addons/surgery/stringtable.xml
Labels: kind/bug fix
