Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-04, with the labels that each got.

#505 Translation - Improve Japanese (Add missing line for Japanese)
  addons/circulation/stringtable.xml
Labels: area/translations

#494 Misc - Add Full Body Stiching
  addons/misc/ACE_Medical_Treatment_Actions.hpp
  addons/misc/XEH_PREP.hpp
  addons/misc/XEH_preInit.sqf
  addons/misc/functions/fnc_canStitchFullBody.sqf
  addons/misc/functions/fnc_getFullBodyStitchableWounds.sqf
  addons/misc/functions/fnc_getStitchTimeFullBody.sqf
  addons/misc/functions/fnc_surgicalKitProgressFullBody.sqf
  addons/misc/stringtable.xml
Labels: kind/feature request

#506 Translation - Improve German translation
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/pharma/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#507 Circulations - Fix minCardiacOutput
  addons/pharma/functions/fnc_alphaAction.sqf
  addons/pharma/functions/fnc_handleRespawn.sqf
  addons/pharma/functions/fnc_init.sqf
Labels: kind/bug fix

#515 Pharma - Add EACA clear trauma setting
  addons/pharma/XEH_preInit.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
  addons/pharma/stringtable.xml
Labels: kind/feature request

#511 Pharma - Fix for broken alpha action
  addons/circulation/functions/fnc_updateInternalBleeding.sqf
  addons/main/script_macros.hpp
  addons/pharma/CfgFunctions.hpp
  addons/pharma/XEH_PREP.hpp
  addons/pharma/functions/fnc_getBloodLoss.sqf
Labels: kind/bug fix

#514 Pharma - Changed Max Dosages
  addons/pharma/ACE_Medical_Treatment.hpp
Labels: kind/enhancement

#517 Breathing - Fix PneumothoraxAlwaysVisible
  addons/breathing/functions/fnc_gui_updateInjuryListWounds.sqf
Labels: kind/bug fix

#513 Breathing - Fix oxygen saturation not deteriorating from airway obstruction
  addons/breathing/functions/fnc_handleBreathing.sqf
Labels: kind/bug fix

#520 Airway/Breathing/Circulation - Fix 0% chance
  addons/airway/functions/fnc_handleAirway.sqf
  addons/breathing/functions/fnc_handlePneumothoraxDeterioration.sqf
  addons/breathing/functions/fnc_handlePulmoHit.sqf
  addons/breathing/functions/fnc_inflictAdvancedPneumothorax.sqf
  addons/circulation/functions/fnc_cprLocal.sqf
Labels: kind/bug fix

#521 Translate - Russian for 2.15
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#458 Chemical - Fix mortar issues
  addons/chemical/CfgMagazineGroups.hpp
  addons/chemical/CfgVehicles.hpp
  addons/chemical/CfgWeapons.hpp
Labels: kind/bug fix
