Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-11, with the labels that each got.

#633 Vitals - Apply SpO2 Multipliers
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#630 Hypothermia - Fix bad interaction condition
  addons/hypothermia/ACE_Medical_Treatment_Actions.hpp
  addons/hypothermia/CfgVehicles.hpp
Labels: kind/enhancement

#638 Pharma/Vitals - Fix negative ECP & ECB volumes and o2Sat calculations at low ECB values
  addons/pharma/functions/fnc_getBloodVolumeChange.sqf
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#637 Breathing - Add CBA setting to enable/disable Check Breathing medical action
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/XEH_preInit.sqf
  addons/breathing/stringtable.xml
Labels: kind/enhancement

#639 Main - Update SpO2 macros to be compatible with ACE SpO2
  addons/breathing/functions/fnc_gui_updateInjuryListPart.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_pulseoximeterLocal.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
  addons/feedback/functions/fnc_handleEffects.sqf
  addons/main/script_macros.hpp
  addons/vitals/functions/fnc_hasStableVitals.sqf
  addons/watch/functions/fnc_showKWatch.sqf
  addons/watch/functions/fnc_showSWatch.sqf
Labels: kind/bug fix

#645 Translations - Italian
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations
