Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-12, with the labels that each got.

#597 Chemical - Improve various aspects
  .hemtt/launch.toml
  addons/chemical/CfgAmmo.hpp
  addons/chemical/CfgCloudlets.hpp
  addons/chemical/CfgGlasses.hpp
  addons/chemical/CfgMagazines.hpp
  addons/chemical/CfgVehicles.hpp
  addons/chemical/XEH_PREP.hpp
  addons/chemical/XEH_postInit.sqf
  addons/chemical/XEH_preInit.sqf
  addons/chemical/config.cpp
  addons/chemical/functions/fnc_AttributeRadius.sqf
  addons/chemical/functions/fnc_CASCreateGas.sqf
  addons/chemical/functions/fnc_GasTripEffect.sqf
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_breathing.sqf
  addons/chemical/functions/fnc_canPutOnGasMask.sqf
  addons/chemical/functions/fnc_canTakeOffGasMask.sqf
  addons/chemical/functions/fnc_changeGasMaskFilter.sqf
  addons/chemical/functions/fnc_chemDetector.sqf
  addons/chemical/functions/fnc_coughing.sqf
  addons/chemical/functions/fnc_createSealAction.sqf
  addons/chemical/functions/fnc_createZone.sqf
  addons/chemical/functions/fnc_csGrenade.sqf
  addons/chemical/functions/fnc_fullHealLocal.sqf
  addons/chemical/functions/fnc_gasAI.sqf
  addons/chemical/functions/fnc_gasCheck.sqf
  addons/chemical/functions/fnc_gasCheckLocal.sqf
  addons/chemical/functions/fnc_gasManagerPFH.sqf
  addons/chemical/functions/fnc_gasmodule.sqf
  addons/chemical/functions/fnc_getChemDetectorState.sqf
  addons/chemical/functions/fnc_handleCSGas.sqf
  addons/chemical/functions/fnc_handleFired.sqf
  addons/chemical/functions/fnc_handleGasMaskDur.sqf
  addons/chemical/functions/fnc_handleRespawn.sqf
  addons/chemical/functions/fnc_init.sqf
  addons/chemical/functions/fnc_poison.sqf
  addons/chemical/functions/fnc_putOnGasMask.sqf
  addons/chemical/functions/fnc_showChemDetector.sqf
  addons/chemical/functions/fnc_spawnSmoke.sqf
  addons/chemical/functions/fnc_takeOffGasMask.sqf
  addons/chemical/functions/fnc_treatmentAdvanced_AtropineLocal.sqf
  addons/chemical/functions/fnc_ui_gasModule.sqf
  addons/chemical/script_component.hpp
  addons/chemical/stringtable.xml
  addons/chemical/ui/RscAttributes.hpp
  addons/feedback/XEH_PREP.hpp
  addons/feedback/functions/fnc_effectCoughing.sqf
  addons/feedback/functions/fnc_effectTearHaze.sqf
  addons/feedback/functions/fnc_handleEffects.sqf
  addons/feedback/functions/fnc_initEffects.sqf
  addons/feedback/script_component.hpp
  addons/main/script_macros.hpp
  addons/vitals/XEH_PREP.hpp
  addons/vitals/functions/fnc_handlePoisoning.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
  addons/vitals/script_component.hpp
Labels: kind/enhancement

#647 Circulation/GUI - Add ABG Setting
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/XEH_preInit.sqf
  addons/circulation/stringtable.xml
  addons/gui/functions/fnc_onMenuOpen.sqf
  addons/gui/functions/fnc_updateABGStatus.sqf
  addons/gui/gui.hpp
  addons/gui/gui_defines.hpp
Labels: kind/enhancement

#641 Vitals - Updates handleOxygenFunction to better handle cardiac arrest and implement perfusion multipliers
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#646 Airway/Breathing/Vitals - Adds Oxygen Mask for High Altitude Operations
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/XEH_PREP.hpp
  addons/airway/functions/fnc_checkMask.sqf
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/CfgMagazines.hpp
  addons/breathing/CfgVehicles.hpp
  addons/breathing/XEH_PREP.hpp
  addons/breathing/XEH_postInit.sqf
  addons/breathing/XEH_preInit.sqf
  addons/breathing/functions/fnc_attachPersonalOxygen.sqf
  addons/breathing/functions/fnc_attachVehicleOxygen.sqf
  addons/breathing/functions/fnc_canUseBVM.sqf
  addons/breathing/functions/fnc_checkAircraftOxygen.sqf
  addons/breathing/functions/fnc_checkPersonalOxygen.sqf
  addons/breathing/functions/fnc_detachPersonalOxygen.sqf
  addons/breathing/functions/fnc_handleRespawn.sqf
  addons/breathing/functions/fnc_init.sqf
  addons/breathing/functions/fnc_removeOxygenMask.sqf
  addons/breathing/stringtable.xml
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/feature request

#642 Translation - Improve Japanese
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/pharma/stringtable.xml
Labels: area/translations

#651 Misc - Fix typo in fnc_carryObject.sqf
  addons/misc/functions/fnc_carryObject.sqf
Labels: kind/bug fix

#653 HEMTT - Fix warnings
  addons/circulation/defines.hpp
  addons/circulation/functions/fnc_AEDX_ViewMonitor_Charging.sqf
  addons/misc/script_component.hpp
Labels: kind/bug fix

#649 Translation - French
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#652 Zeus - Remove unnecessary zeus module
  addons/zeus/CfgVehicles.hpp
  addons/zeus/XEH_PREP.hpp
  addons/zeus/config.cpp
  addons/zeus/functions/fnc_openMedicalMenu.sqf
  addons/zeus/stringtable.xml
Labels: area/compatibility

#654 Breathing - Fix OxyMaskList variable and O2 Mask recognition
  addons/breathing/CfgVehicles.hpp
  addons/breathing/XEH_PREP.hpp
  addons/breathing/XEH_postInit.sqf
  addons/breathing/XEH_preInit.sqf
  addons/breathing/functions/fnc_checkOxygenMask.sqf
Labels: kind/bug fix

#648 Pharma/Surgery - Tweak open reduction PFH and etomidate time
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/surgery/XEH_preInit.sqf
  addons/surgery/functions/fnc_incisionLocal.sqf
Labels: kind/enhancement

#650 Chemical - Add missing entries and zones
  addons/chemical/XEH_preInit.sqf
  addons/chemical/functions/fnc_fullHealLocal.sqf
  addons/chemical/functions/fnc_gasManagerPFH.sqf
  addons/chemical/functions/fnc_gasmodule.sqf
  addons/chemical/functions/fnc_poison.sqf
  addons/chemical/functions/fnc_ui_gasModule.sqf
  addons/chemical/script_component.hpp
  addons/chemical/stringtable.xml
  addons/vitals/functions/fnc_handlePoisoning.sqf
  addons/vitals/functions/fnc_handleSimpleVitals.sqf
Labels: kind/bug fix

#658 Breathing - Re-add sounds for Breathing/Chemical conditions
  addons/breathing/XEH_PREP.hpp
  addons/breathing/XEH_postInit.sqf
  addons/breathing/functions/fnc_handleBreathingConditions.sqf
  addons/chemical/CfgSounds.hpp
  addons/chemical/audio/cough_0.ogg
  addons/chemical/audio/cough_1.ogg
  addons/chemical/audio/cough_2.ogg
  addons/chemical/audio/cough_3.ogg
  addons/chemical/functions/fnc_fullHealLocal.sqf
  addons/chemical/functions/fnc_poison.sqf
  addons/feedback/XEH_PREP.hpp
  addons/feedback/functions/fnc_effectBreathingWheeze.sqf
  addons/feedback/functions/fnc_effectCoughing.sqf
  addons/feedback/functions/fnc_handleEffects.sqf
Labels: kind/bug fix

#661 Watch - Add New Watch
  addons/watch/CfgSounds.hpp
  addons/watch/CfgWeapons.hpp
  addons/watch/RscTitles.hpp
  addons/watch/UI/RangerWatchCaps.paa
  addons/watch/UI/RangerWatchCompass.paa
  addons/watch/UI/RangerWatchDarkSheet.paa
  addons/watch/UI/RangerWatchFace.paa
  addons/watch/UI/RangerWatchHour.paa
  addons/watch/UI/RangerWatchMinute.paa
  addons/watch/UI/RangerWatchNVGSheet.paa
  addons/watch/UI/RangerWatchSecond.paa
  addons/watch/XEH_PREP.hpp
  addons/watch/XEH_postInit.sqf
  addons/watch/audio/watchAlarm.ogg
  addons/watch/audio/watchAlarm.xmp
  addons/watch/audio/watchVibrate.ogg
  addons/watch/audio/watchVibrate.xmp
  addons/watch/config.cpp
  addons/watch/functions/fnc_closeWatchTimer.sqf
  addons/watch/functions/fnc_handleRespawn.sqf
  addons/watch/functions/fnc_hideRWatch.sqf
  addons/watch/functions/fnc_init.sqf
  addons/watch/functions/fnc_showRWatch.sqf
  addons/watch/stringtable.xml
Labels: kind/feature request

#659 Chemical - Change Chemical Detector Sound
  addons/chemical/CfgSounds.hpp
  addons/chemical/CfgVehicles.hpp
  addons/chemical/XEH_PREP.hpp
  addons/chemical/XEH_postInit.sqf
  addons/chemical/audio/baseChime.ogg
  addons/chemical/audio/fastChime.ogg
  addons/chemical/audio/normalChime.ogg
  addons/chemical/audio/rapidChime.ogg
  addons/chemical/audio/slowChime.ogg
  addons/chemical/audio/tone.ogg
  addons/chemical/functions/fnc_enableChemDetector.sqf
  addons/chemical/functions/fnc_handleRespawn.sqf
  addons/chemical/functions/fnc_hasDetector.sqf
  addons/chemical/functions/fnc_init.sqf
  addons/chemical/functions/fnc_showChemDetector.sqf
  addons/chemical/stringtable.xml
Labels: kind/enhancement

#657 Airway/Breathing/Chemical - Add option for intoxication status visibility
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/functions/fnc_checkAirway.sqf
  addons/airway/stringtable.xml
  addons/breathing/functions/fnc_checkBreathing.sqf
  addons/chemical/XEH_preInit.sqf
  addons/chemical/functions/fnc_gui_updateBodyImage.sqf
  addons/chemical/functions/fnc_gui_updateInjuryListGeneral.sqf
  addons/chemical/stringtable.xml
Labels: kind/enhancement

#660 Breathing/Chemical - Adds Low O2 Warning Tone and Chemical Compatibility
  addons/breathing/CfgMagazines.hpp
  addons/breathing/CfgSounds.hpp
  addons/breathing/XEH_postInit.sqf
  addons/breathing/audio/respiratorTone.ogg
  addons/breathing/functions/fnc_attachPersonalOxygen.sqf
  addons/breathing/functions/fnc_attachVehicleOxygen.sqf
  addons/chemical/functions/fnc_poison.sqf
Labels: kind/enhancement

#656 French Translation
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
Labels: area/translations

#665 Chemical/Circulation/Watch - Fix Testing Errors
  addons/chemical/functions/fnc_poison.sqf
  addons/circulation/CfgVehicles.hpp
  addons/circulation/functions/fnc_addArterialApplyActions.sqf
  addons/circulation/functions/fnc_addArterialTestActions.sqf
  addons/circulation/functions/fnc_attachBloodGas.sqf
  addons/circulation/functions/fnc_showBloodGas.sqf
  addons/watch/XEH_PREP.hpp
  addons/watch/XEH_postInit.sqf
  addons/watch/functions/fnc_handleRespawn.sqf
  addons/watch/functions/fnc_showRWatch.sqf
  addons/watch/functions/fnc_startWatchTimer.sqf
Labels: kind/bug fix

#663 Compat RHS USF - Add compatibility for stretcher
  .hemtt/launch.toml
  addons/compat_rhs_usf3/$PBOPREFIX$
  addons/compat_rhs_usf3/CfgVehicles.hpp
  addons/compat_rhs_usf3/config.cpp
  addons/compat_rhs_usf3/script_component.hpp
  addons/stretcher/functions/fnc_attachStretcher.sqf
  addons/stretcher/vehicle_stretcher.hpp
  optionals/usaf/$PBOPREFIX$
  optionals/usaf/CfgVehicles.hpp
  optionals/usaf/script_component.hpp
Labels: area/compatibility

#669 Translation - Improve Japanese (missed in 3.0.4)
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/surgery/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#674 Translation - Improve Chinesesimp
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#666 Chemical - Fix bad gas type in zeus placed zone
  addons/chemical/CfgVehicles.hpp
  addons/chemical/functions/fnc_gasmodule.sqf
  addons/chemical/stringtable.xml
  addons/chemical/ui/RscAttributes.hpp
Labels: kind/bug fix

#672 Translation - Improve French
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#676 Translation - Improve Japanese (Gas, Saline)
  addons/chemical/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations
