Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-09, with the labels that each got.

#591 General - Fix command case
  addons/airway/functions/fnc_gui_updateInjuryListGeneral.sqf
  addons/airway/functions/fnc_gui_updateInjuryListPart.sqf
  addons/airway/functions/fnc_handlePuking.sqf
  addons/airway/functions/fnc_treatmentAdvanced_RemoveAirwayItemLocal.sqf
  addons/breathing/functions/fnc_gui_updateInjuryListPart.sqf
  addons/breathing/functions/fnc_handlePulmoHit.sqf
  addons/breathing/functions/fnc_useBVM.sqf
  addons/chemical/functions/fnc_afterWait.sqf
  addons/chemical/functions/fnc_chemDetector.sqf
  addons/chemical/functions/fnc_gasAI.sqf
  addons/chemical/functions/fnc_gasCheck.sqf
  addons/chemical/functions/fnc_getChemDetectorState.sqf
  addons/chemical/functions/fnc_getList.sqf
  addons/chemical/functions/fnc_handleFired.sqf
  addons/chemical/functions/fnc_init.sqf
  addons/chemical/functions/fnc_throwGrenade.sqf
  addons/circulation/defines.hpp
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
  addons/circulation/functions/fnc_AED_Analyze.sqf
  addons/circulation/functions/fnc_AED_Charge.sqf
  addons/circulation/functions/fnc_Defibrillator_AttachPads.sqf
  addons/circulation/functions/fnc_Defibrillator_ManualCharge.sqf
  addons/circulation/functions/fnc_updateBloodPressureChange.sqf
  addons/hypothermia/functions/fnc_checkHandWarmers.sqf
  addons/misc/functions/fnc_BubbleWrap.sqf
  addons/misc/functions/fnc_FAK_checkRepack.sqf
  addons/misc/functions/fnc_FAK_displayContent.sqf
  addons/misc/functions/fnc_FAK_repack.sqf
  addons/misc/functions/fnc_FAK_unpack.sqf
  addons/misc/functions/fnc_FAK_updateContents.sqf
  addons/misc/functions/fnc_stringToArray.sqf
  addons/misc/functions/fnc_unSlingArmband.sqf
  addons/misc/functions/fnc_unloadAndCarryPatient.sqf
  addons/pharma/functions/fnc_clotWound.sqf
  addons/pharma/functions/fnc_getBloodVolumeChange.sqf
  addons/surgery/functions/fnc_closedReductionLocal.sqf
  addons/zeus/functions/fnc_openMedicalMenu.sqf
  addons/zeus/functions/fnc_toggleAIDeathModule.sqf
  addons/zeus/functions/fnc_ui_changeBloodType.sqf
  addons/zeus/functions/fnc_ui_changeCardiacState.sqf
  addons/zeus/functions/fnc_ui_manageAirway.sqf
Labels: ignore changelog, kind/cleanup

#592 HEMTT - Clean up toml files for HEMTT 1.13
  .hemtt/launch.toml
  .hemtt/project.toml
Labels: ignore changelog, kind/cleanup

#595 CI - Fix HEMTT CI artifacts not uploaded
  .github/workflows/arma.yml
Labels: ignore changelog, kind/bug fix

#599 Circulation - Fix ETCo2 Monitor
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
Labels: kind/cleanup

#600 Translations - Add Dutch translations
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations
