Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-01, with the labels that each got.

#461 Translation - Improve french translation
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations

#455 Fix - Category, Unpacking & Repacking of IFAK, AFAK & MFAK
  addons/misc/CfgWeapons.hpp
  addons/misc/functions/fnc_FAK_repack.sqf
  addons/misc/functions/fnc_FAK_unpack.sqf
Labels: kind/bug fix

#457 Airway/Misc - Fixes for surgical kit autoclosing menu, weapon sway, recovery position
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/functions/fnc_treatmentAdvanced_RecoveryPositionLocal.sqf
  addons/misc/XEH_postInit.sqf
  addons/misc/functions/fnc_fullHealLocal.sqf
  addons/misc/functions/fnc_handleRespawn.sqf
  addons/misc/functions/fnc_treatmentSuccess.sqf
Labels: kind/bug fix

#466 Misc - Remove unused KAM medical category for ace arsenal
  addons/misc/XEH_preInit.sqf
Labels: kind/cleanup

#453 Airway - Add Manual Suction Pump
  README.md
  addons/airway/ACE_Medical_Treatment_Actions.hpp
  addons/airway/CfgVehicles.hpp
  addons/airway/CfgWeapons.hpp
  addons/airway/XEH_preInit.sqf
  addons/airway/config.cpp
  addons/airway/functions/fnc_treatmentAdvanced_Accuvac.sqf
  addons/airway/functions/fnc_treatmentAdvanced_AccuvacStart.sqf
  addons/airway/sounds/accuvac_start.wav
  addons/airway/sounds/accuvac_suction.wav
  addons/airway/sounds/manualpump_start.wav
  addons/airway/sounds/manualpump_suction.wav
  addons/airway/stringtable.xml
  addons/airway/ui/suction.paa
  addons/airway/ui/suction_normal.paa
  addons/breathing/CfgVehicles.hpp
Labels: kind/feature request

#467 Spanish Translation
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/misc/stringtable.xml
Labels: area/translations
