Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-10, with the labels that each got.

#603 Pharma - Fix Carbonate and reorientation
  addons/pharma/functions/fnc_treatmentAdvanced_CarbonateLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_ReorientationLocal.sqf
Labels: kind/bug fix

#605 Hypothermia/Pharma/Vitals - Dev Vital Fixes
  addons/pharma/functions/fnc_getBloodVolumeChange.sqf
  addons/vitals/functions/fnc_handleTemperatureFunction.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
  addons/zeus/stringtable.xml
Labels: kind/bug fix

#594 Feedback - Add new addon
  addons/breathing/XEH_PREP.hpp
  addons/breathing/XEH_postInit.sqf
  addons/breathing/XEH_preInit.sqf
  addons/breathing/functions/fnc_handleBreathing.sqf
  addons/breathing/functions/fnc_lowSpO2pp.sqf
  addons/breathing/stringtable.xml
  addons/feedback/$PBOPREFIX$
  addons/feedback/CfgEventHandlers.hpp
  addons/feedback/XEH_PREP.hpp
  addons/feedback/XEH_postInit.sqf
  addons/feedback/XEH_preInit.sqf
  addons/feedback/config.cpp
  addons/feedback/functions/fnc_effectLowSpO2.sqf
  addons/feedback/functions/fnc_effectOpioid.sqf
  addons/feedback/functions/fnc_handleEffects.sqf
  addons/feedback/functions/fnc_initEffects.sqf
  addons/feedback/script_component.hpp
  addons/feedback/stringtable.xml
  addons/main/script_macros.hpp
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/XEH_PREP.hpp
  addons/pharma/XEH_preInit.sqf
  addons/pharma/functions/fnc_fullHealLocal.sqf
  addons/pharma/functions/fnc_medicationLocal.sqf
  addons/pharma/functions/fnc_pervitinPP.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_FentanylLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_KetamineLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_MorphineLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_NalbuphineLocal.sqf
  addons/pharma/stringtable.xml
  addons/vitals/CfgFunctions.hpp
  addons/vitals/XEH_PREP.hpp
  addons/vitals/functions/fnc_addMedicationAdjustment.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
  addons/vitals/functions/fnc_updateOpioidEffect.sqf
Labels: kind/enhancement

#601 Translation - Improve Spanish language to 3.0.0
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#598 Pharma- Fix Coag sense showing INR as normal when it is not
  addons/pharma/functions/fnc_treatmentAdvanced_CheckCoag.sqf
Labels: kind/bug fix

#606 Pharma - Remove old version of changing alpha action
  addons/circulation/functions/fnc_updateInternalBleeding.sqf
  addons/pharma/XEH_PREP.hpp
  addons/pharma/functions/fnc_alphaAction.sqf
  addons/pharma/functions/fnc_medicationLocal.sqf
Labels: area/compatibility

#596 Translation - Improve Japanese for 3.0.0
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#607 Pharma - Fix missing description of Coag Sense
  addons/pharma/CfgWeapons.hpp
Labels: kind/cleanup

#609 General - Implement CBA versioning system
  addons/main/CfgSettings.hpp
  addons/main/config.cpp
  addons/main/script_mod.hpp
Labels: kind/feature request

#608 General - Fix for ace update 3.18
  addons/circulation/functions/fnc_updateHeartRate.sqf
  addons/gui/functions/fnc_menuPFH.sqf
  addons/misc/functions/fnc_canCheckDogtag.sqf
  addons/misc/functions/fnc_carryObject.sqf
  addons/misc/functions/fnc_treatment.sqf
  addons/misc/functions/fnc_updateDamageEffects.sqf
  addons/misc/functions/fnc_useItem.sqf
  addons/pharma/functions/fnc_medicationLocal.sqf
  addons/pharma/functions/fnc_tourniquetRemove.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
Labels: kind/bug fix

#611 Circulation/Feedback/GUI/Hypothermia/Pharma - 3.0 Hotfix
  addons/circulation/XEH_preInit.sqf
  addons/circulation/functions/fnc_addArterialApplyActions.sqf
  addons/circulation/functions/fnc_addArterialTestActions.sqf
  addons/circulation/functions/fnc_drawArterial.sqf
  addons/circulation/functions/fnc_fullHealLocal.sqf
  addons/circulation/functions/fnc_showBloodGas.sqf
  addons/feedback/XEH_preInit.sqf
  addons/gui/XEH_PREP.hpp
  addons/gui/functions/fnc_handleABGShow.sqf
  addons/gui/functions/fnc_handleIVShow.sqf
  addons/gui/functions/fnc_onMenuOpen.sqf
  addons/gui/functions/fnc_updateABGStatus.sqf
  addons/gui/functions/fnc_updateIVStatus.sqf
  addons/gui/gui.hpp
  addons/gui/gui_defines.hpp
  addons/hypothermia/XEH_preInit.sqf
  addons/pharma/XEH_preInit.sqf
  addons/pharma/functions/fnc_fullHealLocal.sqf
  addons/pharma/stringtable.xml
Labels: kind/bug fix

#614 BOM Encoding
  addons/airway/licence.txt
  addons/breathing/licence.txt
  addons/circulation/licence.txt
  addons/misc/licence.txt
  addons/pharma/licence.txt
Labels: kind/bug fix

#617 Vitals - Fix updatevitals event removal
  addons/vitals/functions/fnc_handleUnitVitals.sqf
Labels: kind/bug fix

#618 GUI/Main/Pharma/Vitals - Blood Pressure and HandleUnitVitals fixes
  addons/circulation/Blood_Medical.hpp
  addons/gui/functions/fnc_updateABGStatus.sqf
  addons/pharma/functions/fnc_getBloodVolumeChange.sqf
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
  addons/vitals/functions/fnc_handleSimpleVitals.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
Labels: kind/bug fix

#620 Translations - Add Chinesesimp translations
  addons/airway/stringtable.xml
  addons/circulation/stringtable.xml
  addons/gui/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#619 Translation - Improve Japanese for 3.0.2
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/pharma/stringtable.xml
Labels: area/translations

#621 Pharma/Vitals - Fix Opioid Factor SPo2
  addons/breathing/XEH_preInit.sqf
  addons/main/script_macros.hpp
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/functions/fnc_fullHealLocal.sqf
  addons/pharma/functions/fnc_medicationLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_FentanylLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_MorphineLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_NalbuphineLocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_NaloxoneLocal.sqf
  addons/vitals/XEH_PREP.hpp
  addons/vitals/XEH_preInit.sqf
  addons/vitals/functions/fnc_addMedicationAdjustment.sqf
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
  addons/vitals/functions/fnc_updateOpioidEffect.sqf
  addons/vitals/functions/fnc_updateOpioidRelief.sqf
Labels: kind/bug fix

#624 Breathing - Update PaCO2 stringtable
  addons/breathing/stringtable.xml
Labels: kind/bug fix

#623 Watch - NEW WATCH ALERT, ONLY $2499.99!!!
  addons/watch/CfgWeapons.hpp
  addons/watch/RscTitles.hpp
  addons/watch/UI/watch_cavmin.paa
  addons/watch/UI/watch_cavmin_compass.paa
  addons/watch/UI/watch_cavmin_face.paa
  addons/watch/UI/watch_sts.paa
  addons/watch/UI/watch_sts_bigAlt.paa
  addons/watch/UI/watch_sts_smallAlt.paa
  addons/watch/XEH_PREP.hpp
  addons/watch/XEH_postInit.sqf
  addons/watch/config.cpp
  addons/watch/functions/fnc_hideCWatch.sqf
  addons/watch/functions/fnc_hideSWatch.sqf
  addons/watch/functions/fnc_showCWatch.sqf
  addons/watch/functions/fnc_showKWatch.sqf
  addons/watch/functions/fnc_showSWatch.sqf
  addons/watch/stringtable.xml
Labels: enhancement

#626 Feedback - Fix incorrect bool in feedback addon
  addons/feedback/functions/fnc_effectLowSpO2.sqf
Labels: kind/bug fix

#627 Watch - Cosmetic Fixes
  addons/watch/RscTitles.hpp
Labels: kind/bug fix

#625 Translation - Improve Japanese and Add missing localization strings
  addons/breathing/stringtable.xml
  addons/pharma/stringtable.xml
  addons/vitals/stringtable.xml
Labels: area/translations

#629 Translation - Improve Japanese again
  addons/watch/stringtable.xml
Labels: area/translations
