Repository KAT-Advanced-Medical/KAM, pull requests merged in 2024-05, with the labels that each got.

#495 Airway/Breathing/Circulation - Add ETCo2 Monitor
  AUTHORS.txt
  addons/airway/functions/fnc_treatmentAdvanced_RemoveAirwayItem.sqf
  addons/airway/functions/fnc_treatmentAdvanced_airwayLocal.sqf
  addons/breathing/ACE_Medical_Treatment_Actions.hpp
  addons/breathing/CfgVehicles.hpp
  addons/breathing/CfgWeapons.hpp
  addons/breathing/XEH_PREP.hpp
  addons/breathing/XEH_postInit.sqf
  addons/breathing/XEH_preInit.sqf
  addons/breathing/config.cpp
  addons/breathing/functions/fnc_fullHealLocal.sqf
  addons/breathing/functions/fnc_getETCo2.sqf
  addons/breathing/functions/fnc_getRespiratoryRate.sqf
  addons/breathing/functions/fnc_gui_updateBodyImage.sqf
  addons/breathing/functions/fnc_gui_updateInjuryListPart.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_nasalCannula.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_nasalCannulaLocal.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_removeNasalCannula.sqf
  addons/breathing/functions/fnc_treatmentAdvanced_removeNasalCannulaLocal.sqf
  addons/breathing/stringtable.xml
  addons/breathing/ui/nasalcannula.paa
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
  addons/circulation/stringtable.xml
  addons/gui/data/body_image/head_nasalcannula.paa
  addons/gui/gui.hpp
  addons/gui/gui_defines.hpp
Labels: kind/feature request

#529 Surgery - Fix Unconsciousness Required for Surgery setting
  addons/surgery/XEH_preInit.sqf
  addons/surgery/functions/fnc_incisionLocal.sqf
Labels: kind/bug fix

#531 Circulation - Fix internal bleeding persisting after respawn
  addons/circulation/functions/fnc_fullHealLocal.sqf
  addons/circulation/functions/fnc_updateInternalBleeding.sqf
Labels: kind/bug fix

#530 Circulation - Fix AED monitor not displaying correct rhythm when dead
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_getCardiacArrestHeartRate.sqf
Labels: kind/bug fix

#538 Airway/Breathing/Circulation - Fix EtCO2 monitor error when AED attached
  addons/circulation/functions/fnc_AEDX_VitalsMonitor.sqf
Labels: kind/bug fix

#539 Revert "Pharma - Fix for broken alpha action"
  addons/circulation/functions/fnc_updateInternalBleeding.sqf
  addons/main/script_macros.hpp
  addons/pharma/CfgFunctions.hpp
  addons/pharma/XEH_PREP.hpp
  addons/pharma/functions/fnc_getBloodLoss.sqf
Labels: ignore changelog

#512 Pharma - Modify ace_medical_status_getBloodLoss for alpha action
  addons/circulation/functions/fnc_updateInternalBleeding.sqf
  addons/pharma/XEH_postInit.sqf
Labels: kind/optimization

#536 Translations - Update Russian
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
Labels: area/translations

#537 Translations - Add French translation
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations
