Repository KAT-Advanced-Medical/KAM, pull requests merged in 2025-04, with the labels that each got.

#752 Add French - Translation - Hypothermia
  addons/hypothermia/stringtable.xml
Labels: area/translations

#296 Ophthalmology - Add manual blinking and eye injuries
  addons/feedback/XEH_PREP.hpp
  addons/feedback/XEH_postInit.sqf
  addons/feedback/data/BlindEffect.paa
  addons/feedback/data/LeftEyeEffect.paa
  addons/feedback/data/LowerBlink.paa
  addons/feedback/data/RightEyeEffect.paa
  addons/feedback/data/UpperBlink.paa
  addons/feedback/functions/fnc_effectEyeBlink.sqf
  addons/feedback/functions/fnc_effectEyeInjury.sqf
  addons/feedback/functions/fnc_effectHurtEye.sqf
  addons/feedback/functions/fnc_handleEffects.sqf
  addons/feedback/functions/fnc_initEffects.sqf
  addons/main/script_macros.hpp
  addons/ophthalmology/$PBOPREFIX$
  addons/ophthalmology/ACE_Medical_Treatment_Actions.hpp
  addons/ophthalmology/CfgEventHandlers.hpp
  addons/ophthalmology/CfgMagazines.hpp
  addons/ophthalmology/CfgWeapons.hpp
  addons/ophthalmology/RscTitles.hpp
  addons/ophthalmology/XEH_PREP.hpp
  addons/ophthalmology/XEH_postInit.sqf
  addons/ophthalmology/XEH_preInit.sqf
  addons/ophthalmology/config.cpp
  addons/ophthalmology/functions/fnc_eyeShieldCondition.sqf
  addons/ophthalmology/functions/fnc_fullHealLocal.sqf
  addons/ophthalmology/functions/fnc_gui_updateInjuryListPart.sqf
  addons/ophthalmology/functions/fnc_handleDustInjury.sqf
  addons/ophthalmology/functions/fnc_handleExplosion.sqf
  addons/ophthalmology/functions/fnc_handleRespawn.sqf
  addons/ophthalmology/functions/fnc_init.sqf
  addons/ophthalmology/functions/fnc_treatmentAdvanced_eyeShield.sqf
  addons/ophthalmology/functions/fnc_treatmentAdvanced_eyewash.sqf
  addons/ophthalmology/initKeybinds.inc.sqf
  addons/ophthalmology/initSettings.inc.sqf
  addons/ophthalmology/models/eyecovers/camo1.rvmat
  addons/ophthalmology/models/eyecovers/camo1_as.paa
  addons/ophthalmology/models/eyecovers/camo1_ca.paa
  addons/ophthalmology/models/eyecovers/camo1_co.paa
  addons/ophthalmology/models/eyecovers/camo1_nohq.paa
  addons/ophthalmology/models/eyecovers/camo1_smdi.paa
  addons/ophthalmology/models/eyecovers/kat_eyecovers.p3d
  addons/ophthalmology/models/eyecovers/model.cfg
  addons/ophthalmology/script_component.hpp
  addons/ophthalmology/stringtable.xml
  addons/ophthalmology/ui/LeftEyeNVG.paa
  addons/ophthalmology/ui/LeftEyeShield.paa
  addons/ophthalmology/ui/LowerBlink.paa
  addons/ophthalmology/ui/RightEyeNVG.paa
  addons/ophthalmology/ui/RightEyeShield.paa
  addons/ophthalmology/ui/UpperBlink.paa
  addons/ophthalmology/ui/icon_eyeshield.paa
  addons/ophthalmology/ui/icon_eyewasher.paa
Labels: kind/feature request

#751 Vitals - Fix ETCO2
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#755 Translations - Czech
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#754 General - Improve CBA Category
  addons/airway/XEH_preInit.sqf
  addons/airway/initSettings.inc.sqf
  addons/airway/script_component.hpp
  addons/airway/stringtable.xml
  addons/breathing/XEH_preInit.sqf
  addons/breathing/initSettings.inc.sqf
  addons/breathing/script_component.hpp
  addons/breathing/stringtable.xml
  addons/chemical/XEH_postInit.sqf
  addons/chemical/XEH_preInit.sqf
  addons/chemical/initSettings.inc.sqf
  addons/chemical/script_component.hpp
  addons/chemical/stringtable.xml
  addons/circulation/XEH_preInit.sqf
  addons/circulation/initSettings.inc.sqf
  addons/circulation/script_component.hpp
  addons/circulation/stringtable.xml
  addons/feedback/XEH_preInit.sqf
  addons/feedback/initSettings.inc.sqf
  addons/feedback/script_component.hpp
  addons/feedback/stringtable.xml
  addons/gui/XEH_preInit.sqf
  addons/gui/initSettings.inc.sqf
  addons/gui/script_component.hpp
  addons/gui/stringtable.xml
  addons/hypothermia/XEH_preInit.sqf
  addons/hypothermia/initSettings.inc.sqf
  addons/hypothermia/script_component.hpp
  addons/hypothermia/stringtable.xml
  addons/main/script_mod.hpp
  addons/misc/XEH_preInit.sqf
  addons/misc/initSettings.inc.sqf
  addons/misc/script_component.hpp
  addons/misc/stringtable.xml
  addons/ophthalmology/initKeybinds.inc.sqf
  addons/ophthalmology/script_component.hpp
  addons/ophthalmology/stringtable.xml
  addons/pharma/XEH_preInit.sqf
  addons/pharma/initSettings.inc.sqf
  addons/pharma/script_component.hpp
  addons/pharma/stringtable.xml
  addons/stretcher/XEH_preInit.sqf
  addons/stretcher/script_component.hpp
  addons/surgery/XEH_preInit.sqf
  addons/surgery/initSettings.inc.sqf
  addons/surgery/script_component.hpp
  addons/surgery/stringtable.xml
  addons/vitals/XEH_preInit.sqf
  addons/vitals/initSettings.inc.sqf
  addons/vitals/script_component.hpp
  addons/vitals/stringtable.xml
  addons/watch/XEH_postInit.sqf
  addons/watch/XEH_preInit.sqf
  addons/watch/initSettings.inc.sqf
  addons/watch/script_component.hpp
  addons/watch/stringtable.xml
  addons/zeus/script_component.hpp
Labels: kind/enhancement

#756 General - Sort stringtables and tidy them up
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/CfgVehicles.hpp
  addons/chemical/stringtable.xml
  addons/circulation/CfgWeapons.hpp
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/main/stringtable.xml
  addons/misc/stringtable.xml
  addons/ophthalmology/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/CfgWeapons.hpp
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
  addons/zeus/stringtable.xml
Labels: kind/enhancement

#758 Translation - French
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/misc/stringtable.xml
  addons/ophthalmology/stringtable.xml
  addons/pharma/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#722 Translation - Improve Japanese (and Simp.Chinese a bit) (3.1.0, eye Injury)
  addons/breathing/stringtable.xml
  addons/ophthalmology/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#762 General - Improve Item Boxes
  addons/airway/CfgVehicles.hpp
  addons/breathing/CfgVehicles.hpp
  addons/breathing/CfgWeapons.hpp
  addons/breathing/stringtable.xml
  addons/chemical/CfgAmmo.hpp
  addons/chemical/CfgMagazines.hpp
  addons/circulation/CfgVehicles.hpp
  addons/circulation/CfgWeapons.hpp
  addons/hypothermia/CfgVehicles.hpp
  addons/misc/CfgVehicles.hpp
  addons/misc/CfgWeapons.hpp
  addons/misc/stringtable.xml
  addons/ophthalmology/CfgVehicles.hpp
  addons/ophthalmology/CfgWeapons.hpp
  addons/ophthalmology/config.cpp
  addons/pharma/CfgVehicles.hpp
  addons/pharma/CfgWeapons.hpp
  addons/stretcher/CfgWeapons.hpp
  addons/surgery/CfgVehicles.hpp
  addons/vitals/CfgVehicles.hpp
  addons/vitals/config.cpp
Labels: kind/enhancement

#763 Vitals - Fix respiratory depth
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#760 General - Fix undefined variables
  addons/airway/XEH_postInit.sqf
  addons/breathing/XEH_postInit.sqf
  addons/breathing/functions/fnc_attachPersonalOxygen.sqf
  addons/chemical/functions/fnc_enableChemDetector.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_addDefibrillatorActions.sqf
  addons/circulation/functions/fnc_handleCardiacArrest.sqf
  addons/hypothermia/functions/fnc_checkHandWarmers.sqf
  addons/misc/functions/fnc_addVehicleUnloadCarryPatientActions.sqf
  addons/misc/functions/fnc_setUnconscious.sqf
  addons/misc/functions/fnc_unSlingArmband.sqf
  addons/misc/functions/fnc_useItem.sqf
  addons/ophthalmology/XEH_postInit.sqf
  addons/ophthalmology/functions/fnc_treatmentAdvanced_eyeShield.sqf
  addons/pharma/XEH_postInit.sqf
  addons/pharma/functions/fnc_coagRegen.sqf
  addons/pharma/functions/fnc_pervitinPP.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_TXALocal.sqf
Labels: kind/bug fix

#765 Surgery - Remove REBOA model
  addons/surgery/CfgWeapons.hpp
Labels: kind/bug fix
