Repository KAT-Advanced-Medical/KAM, pull requests merged in 2025-02, with the labels that each got.

#727 Pharma, Fix CWMP And Caffeine Treatment times and med level required
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/XEH_preInit.sqf
  addons/pharma/stringtable.xml
Labels: kind/bug fix

#731 Improve Chinese Translation
  AUTHORS.txt
  addons/airway/stringtable.xml
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/feedback/stringtable.xml
  addons/gui/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/misc/stringtable.xml
  addons/pharma/stringtable.xml
  addons/stretcher/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
  addons/zeus/stringtable.xml
Labels: area/translations

#732 Pharma - Improve ACE Painkillers
  addons/pharma/ACE_Medical_Treatment.hpp
Labels: kind/enhancement

#728 Translation - French
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#734 Translation - Improve Japanese and Fix Chinese (3.0.6)
  AUTHORS.txt
  addons/breathing/stringtable.xml
  addons/circulation/stringtable.xml
  addons/pharma/stringtable.xml
Labels: area/translations

#735 Circulation - Check pulse fixes
  addons/circulation/functions/fnc_checkPulseLocal.sqf
  addons/circulation/functions/fnc_checkPulseStethLocal.sqf
Labels: kind/bug fix

#709 Watch/Vitals - ACE Advanced Fatigue Integration
  addons/vitals/functions/fnc_handleCardiacFunction.sqf
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
  addons/watch/XEH_preInit.sqf
  addons/watch/functions/fnc_init.sqf
  addons/watch/functions/fnc_showCWatch.sqf
  addons/watch/functions/fnc_showKWatch.sqf
  addons/watch/functions/fnc_showRWatch.sqf
  addons/watch/functions/fnc_showSWatch.sqf
  addons/watch/stringtable.xml
Labels: kind/feature request
