Repository KAT-Advanced-Medical/KAM, pull requests merged in 2025-03, with the labels that each got.

#738 Tweak Traditional Chinese
  addons/circulation/stringtable.xml
  addons/hypothermia/stringtable.xml
Labels: area/translations

#743 Brething - Fix condition for checkBreathing
  addons/breathing/functions/fnc_checkBreathing.sqf
Labels: kind/bug fix

#737 Vitals - Fix handleOxygenFunction RPT Spam
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#740 Vitals - Fix _woundBloodLoss being used before init
  addons/vitals/functions/fnc_handleUnitVitals.sqf
Labels: kind/bug fix

#742 Stretcher - Remove ACRE2 intercom and infantry phone
  addons/stretcher/CfgVehicles.hpp
Labels: kind/enhancement

#741 Surgery - Change Clotting Values
  addons/surgery/ACE_Medical_Treatment.hpp
Labels: kind/enhancement

#745 Vitals - Fix Fatigue Integration
  addons/vitals/functions/fnc_handleCardiacFunction.sqf
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
Labels: kind/bug fix

#747 Vitals - Add RemoveStamina Compatibility
  addons/vitals/XEH_PREP.hpp
  addons/vitals/functions/fnc_fullHealLocal.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
  addons/vitals/functions/fnc_returnFatigue.sqf
Labels: kind/enhancement

#750 Vitals - Fix ETCO2
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/bug fix

#749 Hypothermia - Fix CBA Setting Category
  addons/hypothermia/stringtable.xml
Labels: kind/bug fix
