Repository KAT-Advanced-Medical/KAM, pull requests merged in 2025-01, with the labels that each got.

#685 Github - Update workflows
  .github/workflows/arma.yml
  .github/workflows/hemtt.yml
Labels: ignore changelog, kind/enhancement

#680 Surgery - Improve surgical incision checks
  addons/surgery/functions/fnc_incisionLocal.sqf
Labels: kind/bug fix

#671 Pharma - Add New CWMP/Carbonate Sound
  addons/pharma/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/CfgSounds.hpp
  addons/pharma/sounds/slap.ogg
  addons/pharma/sounds/take_CWMP.ogg
  addons/pharma/sounds/take_painkillers.ogg
  addons/pharma/sounds/take_painkillers.wav
  addons/pharma/sounds/use_carbonate.ogg
  addons/pharma/sounds/use_penthrox.ogg
  addons/pharma/sounds/use_penthrox.wav
Labels: kind/enhancement

#668 Breathing - Move pneumo hit handling to wounds handler
  addons/breathing/ACE_Medical_Injuries.hpp
  addons/breathing/XEH_PREP.hpp
  addons/breathing/config.cpp
  addons/breathing/functions/fnc_handlePulmoHit.sqf
  addons/breathing/functions/fnc_woundsHandlerPulmoHit.sqf
Labels: kind/optimization

#689 Breathing/Surgery - Add Complication from Pericardial Tap
  addons/breathing/XEH_PREP.hpp
  addons/breathing/functions/fnc_createTamponade.sqf
  addons/breathing/functions/fnc_woundsHandlerPulmoHit.sqf
  addons/surgery/functions/fnc_pericardialTapLocal.sqf
Labels: kind/enhancement

#687 Vitals - Change pH Function
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/enhancement

#688 Surgery - Update Ultrasound to handle dead patients
  addons/surgery/functions/fnc_ultraAssessmentLocal.sqf
  addons/surgery/stringtable.xml
Labels: kind/bug fix

#692 Circulation - Cardiac Arrest Hold for H&T Conditions
  addons/circulation/XEH_preInit.sqf
  addons/circulation/functions/fnc_cprLocal.sqf
  addons/circulation/stringtable.xml
Labels: kind/enhancement

#693 Circulation - Add ETCO2 and Respiratory Rate monitoring to AED-X Visual Monitor
  addons/circulation/RscTitles.hpp
  addons/circulation/defines.hpp
  addons/circulation/functions/fnc_AEDX_ViewMonitor.sqf
  addons/circulation/functions/fnc_AEDX_ViewMonitor_CPR.sqf
  addons/circulation/ui/AEDX_Monitor_Dialog.hpp
Labels: kind/enhancement

#696 General - Fix broken inheritance
  addons/airway/CfgVehicles.hpp
  addons/breathing/CfgVehicles.hpp
  addons/chemical/CfgVehicles.hpp
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/CfgVehicles.hpp
  addons/misc/ACE_Medical_Treatment_Actions.hpp
  addons/pharma/CfgVehicles.hpp
  addons/stretcher/CfgVehicles.hpp
  addons/surgery/CfgVehicles.hpp
Labels: ignore changelog, kind/bug fix

#705 Chemical - Add ChemicalDetector ground model use Enoch model
  addons/chemical/CfgWeapons.hpp
Labels: kind/enhancement

#702 Breathing - Add Stamina Condition for Chemical Masks
  addons/breathing/functions/fnc_handleBreathingConditions.sqf
  addons/chemical/XEH_preInit.sqf
  addons/chemical/stringtable.xml
Labels: kind/feature request

#703 Circulation - Fixes AED showing AED-X Monitor during CPR
  addons/circulation/functions/fnc_CPRStart.sqf
Labels: kind/bug fix

#700 Watch - Add Controls to KATMIN and Model R Watch to add seconds to time and remove watch hands
  addons/watch/RscTitles.hpp
  addons/watch/XEH_postInit.sqf
  addons/watch/functions/fnc_handleRespawn.sqf
  addons/watch/functions/fnc_init.sqf
  addons/watch/functions/fnc_showKWatch.sqf
  addons/watch/functions/fnc_showRWatch.sqf
  addons/watch/stringtable.xml
Labels: kind/enhancement

#698 Surgery/Vitals - Add REBOA Impacts for CPR Success Rate and Dead/Cardiac Arrest Blood Volume Checks
  addons/circulation/functions/fnc_cprLocal.sqf
  addons/main/script_macros.hpp
  addons/surgery/XEH_PREP.hpp
  addons/surgery/functions/fnc_reboaVolume.sqf
  addons/vitals/functions/fnc_handleUnitVitals.sqf
Labels: kind/enhancement

#707 Misc - Fix Full Body Stitch not working while sutures are needed
  addons/misc/functions/fnc_canStitchFullBody.sqf
Labels: kind/bug fix

#719 Hypothermia - Fix Fluid Warmer application not always showing
  addons/hypothermia/functions/fnc_applyFluidWarmerLocal.sqf
Labels: kind/bug fix

#716 Breathing - Add Helmet Compatibility for Vehicle/Personal Oxygen Lines
  addons/breathing/XEH_postInit.sqf
  addons/breathing/XEH_preInit.sqf
  addons/breathing/functions/fnc_attachPersonalOxygen.sqf
  addons/breathing/functions/fnc_attachVehicleOxygen.sqf
  addons/breathing/functions/fnc_checkOxygenMask.sqf
  addons/breathing/stringtable.xml
  addons/chemical/CfgSounds.hpp
Labels: kind/enhancement

#715 Surgery - Add Ultrasound Airway Condition
  addons/surgery/functions/fnc_ultraAssessmentLocal.sqf
  addons/surgery/stringtable.xml
Labels: kind/enhancement

#706 Translation - French
  addons/breathing/stringtable.xml
  addons/chemical/stringtable.xml
  addons/circulation/stringtable.xml
  addons/surgery/stringtable.xml
  addons/vitals/stringtable.xml
  addons/watch/stringtable.xml
Labels: area/translations

#720 Vitals - Fix Cardiac Fuction QEGVAR
  addons/vitals/functions/fnc_handleCardiacFunction.sqf
Labels: kind/bug fix

#711 Circulation - Add Nitroglycerin Impacts to Cardiac Arrest Chance and Adjust H&T Factor Impact
  addons/circulation/functions/fnc_cprLocal.sqf
  addons/circulation/functions/fnc_handleCardiacArrest.sqf
Labels: kind/enhancement

#710 Vitals - Adjust EtCO2 in Cardiac Arrest
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/enhancement

#714 Hypotherma/Vitals - Adjust Temperature Calculations
  addons/hypothermia/functions/fnc_checkTemperature.sqf
  addons/hypothermia/stringtable.xml
  addons/vitals/functions/fnc_handleTemperatureFunction.sqf
Labels: kind/enhancement

#712 Translation - Improve Japanese (3.0.5 Part2)
  addons/breathing/stringtable.xml
  addons/hypothermia/stringtable.xml
  addons/surgery/stringtable.xml
Labels: area/translations

#675 Pharma, Vitals - Update overrides for ACE update
  .hemtt/launch.toml
  addons/gui/functions/fnc_menuPFH.sqf
  addons/gui/functions/fnc_updateBodyImage.sqf
  addons/gui/functions/fnc_updateInjuryList.sqf
  addons/misc/functions/fnc_treatment.sqf
  addons/misc/functions/fnc_treatmentIV.sqf
  addons/misc/functions/fnc_useItem.sqf
  addons/pharma/ACE_Medical_Treatment.hpp
  addons/pharma/functions/fnc_applyIV.sqf
  addons/pharma/functions/fnc_clotWound.sqf
  addons/pharma/functions/fnc_getBloodVolumeChange.sqf
  addons/pharma/functions/fnc_medicationLocal.sqf
  addons/pharma/functions/fnc_tourniquetRemove.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
  addons/pharma/functions/fnc_treatmentAdvanced_TXALocal.sqf
  addons/surgery/functions/fnc_closedReductionLocal.sqf
  addons/surgery/functions/fnc_incisionLocal.sqf
  addons/vitals/functions/fnc_addMedicationAdjustment.sqf
Labels: kind/bug fix

#724 Surgery - Fix Pericardial Tap
  addons/surgery/functions/fnc_pericardialTapLocal.sqf
Labels: kind/bug fix

#602 Circulation - Add/Change BP and HR default behavior
  addons/breathing/CfgWeapons.hpp
  addons/circulation/ACE_Medical_Treatment_Actions.hpp
  addons/circulation/CfgWeapons.hpp
  addons/circulation/XEH_PREP.hpp
  addons/circulation/XEH_postInit.sqf
  addons/circulation/XEH_preInit.sqf
  addons/circulation/functions/fnc_checkBloodPressure.sqf
  addons/circulation/functions/fnc_checkBloodPressureCuff.sqf
  addons/circulation/functions/fnc_checkBloodPressureCuffLocal.sqf
  addons/circulation/functions/fnc_checkBloodPressureLocal.sqf
  addons/circulation/functions/fnc_checkPulse.sqf
  addons/circulation/functions/fnc_checkPulseLocal.sqf
  addons/circulation/functions/fnc_checkPulseSteth.sqf
  addons/circulation/functions/fnc_checkPulseStethLocal.sqf
  addons/circulation/stringtable.xml
  addons/circulation/ui/BPCuff.paa
Labels: kind/feature request

#643 Vitals - Improve oxygen function to handle respiratory depression
  addons/breathing/functions/fnc_checkBreathing.sqf
  addons/breathing/stringtable.xml
  addons/main/script_macros.hpp
  addons/vitals/functions/fnc_fullHealLocal.sqf
  addons/vitals/functions/fnc_handleOxygenFunction.sqf
Labels: kind/enhancement
